#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
polybar example &
picom &
feh --bg-fill ~/Downloads/10us9paizqc51.jpg  &
xrandr --output DP-0 --rate 75



bspc monitor DP-0 -d 1 2 3 4 5 6 7 8 9 10
bspc monitor HDMI-0 -d 1 2 3 4 5 6 7 8 9 10
bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

xsetroot -cursor_name left_ptr &
